# Generated by Django 5.1.7 on 2025-03-17 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_is_active_alter_customuser_is_staff'),
    ]

    operations = [
    ]
