# Generated by Django 5.1.7 on 2025-04-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskattachment_taskcomment_commentattachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentAttachment',
        ),
    ]
